#!/bin/bash -e

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

sudo apt-get install -y build-essential golang openjdk-8-jdk snapd

sudo snap install kotlin --classic


# Do this last, it might not work
cd /tmp
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup; sh rustup -y

