#!/bin/bash -e

readlink_f() { which greadlink > /dev/null && greadlink -f $1 || readlink -f $1; }
script_dir="$( cd "$(dirname "$( readlink_f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

curl -L https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
sudo echo "deb https://deb.nodesource.com/node_12.x $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/node.list

sudo apt-get update
sudo apt-get install -y --no-install-recommends nodejs

