#!/bin/bash -e

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }


# ---------------------------------------------------------------------------------------------------------------------
# Install vault from hashicorps apt repo
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update
sudo apt-get install -y --no-install-recommends terraform



