#!/bin/bash -e

sudo apt-get install -y apt-transport-https ca-certificates software-properties-common gnupg-agent

curl -L https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo echo "deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list

sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io

# Install docker-compose and completion
sudo curl -sSL "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-Linux-x86_64" -o /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose
sudo curl -sSL "https://raw.githubusercontent.com/docker/compose/1.25.4/contrib/completion/bash/docker-compose" -o /etc/bash_completion.d/docker-compose
sudo curl -sSL "https://github.com/docker/machine/releases/download/v0.16.0/docker-compose-Linux-x86_64" -o /usr/bin/docker-machine
sudo chmod +x /usr/bin/docker-machine
sudo curl -sSL "https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine-prompt.bash" -o /etc/bash_completion.d/docker-machine-prompt.bash
sudo curl -sSL "https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine-wrapper.bash" -o /etc/bash_completion.d/docker-machine-wrapper.bash
sudo curl -sSL "https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash" -o /etc/bash_completion.d/docker-machine.bash

# TODO: pull alpine image


