#!/bin/bash -e

# readlink_f() { which greadlink > /dev/null && greadlink -f $1 || readlink -f $1; }
# script_dir="$( cd "$(dirname "$( readlink_f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

vimver="$(vim --version | grep ', compiled' | grep -E -o -i 'vim - vi improved \S+' | grep -E -o '[0-9]+\.[0-9]+')"
if ! [[ $vimver =~ ^8[.] ]]; then
  sudo add-apt-repository -y ppa:jonathonf/vim
  sudo apt-get update
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends vim


  # ------------------------------------------------------------------------------------------------
  # vimrc
  cat << 'EOF' >> /home/ubuntu/.vimrc
:let mapleader = ","
:set nocompatible

:set hidden
:set showcmd
:set nu
:syntax on
:set ruler
:set clipboard=unnamed
":set autoread
highlight StatusLine ctermfg=blue ctermbg=yellow

filetype plugin indent on

" Whitespace
:set nowrap
:set tabstop=2
:set shiftwidth=2
:set expandtab
:set smartindent
:set backspace=indent,eol,start

" Searching
:set hlsearch
:set incsearch
:set ignorecase
:set smartcase

" Next / Previous tab
:map <F7> :tabp<CR>
:map <F8> :tabn<CR>

" Open file from the same dir
:map <Leader>e :e <C-R>=expand("%:p:h") . '/'<CR>

" Clear search
nmap <silent> ,. :nohlsearch<CR>

:color desert

EOF

  chownmod ubuntu:ubuntu 0644 /home/ubuntu/.vimrc
fi



# ----- vimcat -----

hash vimcat 2> /dev/null && exit 0

if ! hash make 2> /dev/null; then
  echo ""
  echo "Build tools are not installed!! Use:"
  echo "   apt-get install -y build-essential"
  echo ""
  echo "or wait 3 seconds to have it installed automagically"
  echo ""
  echo ""

  sleep 3

  sudo apt-get install -y --no-install-recommends build-essential
  # exit 99
fi

# pandoc and doctoc are optional.  Only install them if requested
if [[ $1 == "--fat" ]]; then
  sudo apt-get install -y pandoc

  if hash npm; then
    sudo npm install --global doctoc
  fi
fi

# clone; make install
mkdir -p "${HOME}/zz_packages/imstall_$$" && cd $_
git clone git://github.com/rkitover/vimpager
cd vimpager
sudo make install-deb

# Clean up
cd "${HOME}/zz_packages"
test -d "imstall_$$" && rm -rf "imstall_$$"

