#!/bin/bash -e

readlink_f() { which greadlink > /dev/null && greadlink -f $1 || readlink -f $1; }
script_dir="$( cd "$(dirname "$( readlink_f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

"${script_dir}/install-nodejs"
"${script_dir}/install-aws"
#"${script_dir}/install-openvpn"
#"${script_dir}/install-consul-server"

sudo sysctl net.ipv4.ip_forward net.ipv4.conf.ens5.forwarding

echo ""
echo "To kick the NAT to get it going again, try:"
echo ""
echo "  sudo sysctl -w net.ipv4.ip_forward=1 net.ipv4.conf.ens5.forwarding=1"
echo ""


