#!/bin/bash -e

readlink_f() { which greadlink > /dev/null && greadlink -f $1 || readlink -f $1; }
script_dir="$( cd "$(dirname "$( readlink_f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

# "${script_dir}/install-nodejs"
# "${script_dir}/install-aws"
# "${script_dir}/install-utilclients"
"${script_dir}/install-git"
#"${script_dir}/install-vault"
#"${script_dir}/install-consul-server"

"${script_dir}/install-docker"
if ! docker network ls | grep -E localnet; then
 docker network create localnet
fi

## TODO: compilers, etc
#"${script_dir}/install-devtools"
#"${script_dir}/install-opstools"


"${script_dir}/install-instance-all"

