#!/bin/bash -e

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

# ================================================================================================================
# Gather necessary settings and data
# ================================================================================================================

# -----------------------------------------------------------------------------
# Get CIDR

IFACE="ens5"
IFACE_MAC=$(cat /sys/class/net/${IFACE}/address)
VPC_CIDR_URI="http://169.254.169.254/latest/meta-data/network/interfaces/macs/${IFACE_MAC}/vpc-ipv4-cidr-block"
VPC_CIDR_RANGE=$(curl --retry 3 --silent --fail "${VPC_CIDR_URI}")



# ================================================================================================================
# Wait for instance to be ready
# ================================================================================================================

# -----------------------------------------------------------------------------
# Wait for cloud-init to finish

for ((i=0;i<120;i+=1)); do
  if grep -E 'Cloud-init.*finished.*Up.*seconds$' /var/log/cloud-init-output.log; then
    sleep 2
    break
  fi

  echo "Waiting for cloud-init to finish. ($(cat /var/log/cloud-init-output.log | wc -l))"
  tail -10 /var/log/cloud-init-output.log
  sleep 1
done

# ================================================================================================================
# Configuration
# ================================================================================================================





























# ================================================================================================================
# Install tools
# ================================================================================================================

sudo apt-get update


# -----------------------------------------------------------------------------
# aws-cli

if ! which aws; then
  if ! which unzip; then
    sudo apt-get install -y unzip
  fi

  cd /tmp/
  curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  unzip awscliv2.zip
  sudo ./aws/install
fi

















# -----------------------------------------------------------------------------
# nodejs

# nodejs
curl -sSL "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" | sudo apt-key add -
echo "deb [ arch=amd64,arm64 ] https://deb.nodesource.com/node_12.x $(lsb_release -cs) main" | sudo tee -a "/etc/apt/sources.list.d/node.list"





sudo apt-get update
sudo apt-get install -y --no-install-recommends nodejs

# Global NPMs
sudo npm install --global pm2
























































