#!/bin/bash -e

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }

# ================================================================================================================
# Gather necessary settings and data
# ================================================================================================================

# -----------------------------------------------------------------------------
# Get CIDR

IFACE="ens5"
IFACE_MAC=$(cat /sys/class/net/${IFACE}/address)
VPC_CIDR_URI="http://169.254.169.254/latest/meta-data/network/interfaces/macs/${IFACE_MAC}/vpc-ipv4-cidr-block"
VPC_CIDR_RANGE=$(curl --retry 3 --silent --fail "${VPC_CIDR_URI}")



# ================================================================================================================
# Wait for instance to be ready
# ================================================================================================================

# -----------------------------------------------------------------------------
# Wait for cloud-init to finish

for ((i=0;i<120;i+=1)); do
  if grep -E 'Cloud-init.*finished.*Up.*seconds$' /var/log/cloud-init-output.log; then
    sleep 2
    break
  fi

  echo "Waiting for cloud-init to finish. ($(cat /var/log/cloud-init-output.log | wc -l))"
  tail -10 /var/log/cloud-init-output.log
  sleep 1
done

# ================================================================================================================
# Configuration
# ================================================================================================================

# -----------------------------------------------------------------------------
# NAT

sudo sysctl -q -w net.ipv4.ip_forward=1 net.ipv4.conf.${IFACE}.forwarding=1
sudo iptables -A FORWARD -o ${IFACE} -j ACCEPT
sudo iptables -A FORWARD -i ${IFACE} -m state --state RELATED,ESTABLISHED -j ACCEPT
#sudo iptables -t nat -A POSTROUTING -o "${IFACE}" -s "${VPC_CIDR_RANGE}" -j MASQUERADE
sudo iptables -t nat -A POSTROUTING -o "${IFACE}" -j MASQUERADE

# Show it worked
[[ -d /home/ubuntu ]] || echo "HOME not up yet???"

if [[ -d /home/ubuntu ]]; then
  touch /home/ubuntu/provision.log
  chown ubuntu:ubuntu /home/ubuntu/provision.log
  chmod 0644 /home/ubuntu/provision.log
  
  sudo sysctl net.ipv4.ip_forward net.ipv4.conf.${IFACE}.send_redirects net.ipv4.conf.${IFACE}.forwarding >> /home/ubuntu/provision.log
  sudo iptables -n -t nat -L POSTROUTING >> /home/ubuntu/provision.log
fi








# ================================================================================================================
# Install tools
# ================================================================================================================

sudo apt-get update


# -----------------------------------------------------------------------------
# aws-cli

if ! which aws; then
  if ! which unzip; then
    sudo apt-get install -y unzip
  fi

  cd /tmp/
  curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  unzip awscliv2.zip
  sudo ./aws/install
fi

















# -----------------------------------------------------------------------------
# nodejs

# nodejs
curl -sSL "https://deb.nodesource.com/gpgkey/nodesource.gpg.key" | sudo apt-key add -
echo "deb https://deb.nodesource.com/node_12.x $(lsb_release -cs) main" | sudo tee -a "/etc/apt/sources.list.d/node.list"





sudo apt-get update
sudo apt-get install -y --no-install-recommends nodejs

# Global NPMs

























































