#!/bin/bash -e

readlink_f() { which greadlink > /dev/null && greadlink -f $1 || readlink -f $1; }
script_dir="$( cd "$(dirname "$( readlink_f "${BASH_SOURCE[0]}" )" )" && pwd )"

errcho() { echo "$@" 1>&2; }
die() { errcho "$@"; exit 1; }





S3_PATH="$1"
USE_SHELL="$2"

[[ -n $USE_SHELL ]] || USE_SHELL="/bin/bash"

if ! which unzip; then
  sleep 10
  sudo apt-get install -y unzip
fi

# if not aws:
if ! which aws; then
  cd /tmp/
  curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  unzip awscliv2.zip
  sudo ./aws/install
fi

aws s3 cp "$S3_PATH" - | $USE_SHELL

